import { colors, fonts } from "../../constants/GlobalStyles";

const { StyleSheet, Dimensions } = require("react-native");


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.mainBackground,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22
  },
  container2: {
    margin: 20,
  },
  label: {
    fontSize: 16,
    marginBottom: 5,
  },
  input: {
    // height: 40,
    // borderColor: 'gray',
    // borderWidth: 1,
    marginBottom: 5,
    padding: 18,
    // flexDirection: "row",
    // alignItems: "center",
    borderWidth: 1,
    borderColor: colors.lightgrey,
    borderRadius: 10,
    height: 60,
    marginBottom: 20,
    backgroundColor: colors.white,
    elevation: 10,
  },
  inBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.lightgrey,
    borderRadius: 10,
    height: 60,
    marginBottom: 20,
    backgroundColor: colors.white,
    elevation: 10,
  },
  innerText: {
    fontFamily: fonts.headerFont,
    left: 20,
    fontSize: 16,
  },
  innerText2: {
    fontFamily: fonts.headerFont,
    left: 30,
    fontSize: 16,
    color: colors.grey,
    width: 180,
    textTransform: "capitalize",
  },
  //   sectionTop: {
  //     flex: 1,
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  //   logo: {
  //     height: 180,
  //     width: 150,
  //     bottom: 20,
  //   },
  //   sectionMiddle: {
  //     flex: 1,
  //     marginHorizontal: 20,
  //   },
  //   inputItem: {
  //     flexDirection: "row",
  //     marginBottom: 10,
  //     borderWidth: 0.5,
  //     borderColor: "gray",
  //     borderRadius: 10,
  //     height: 50,
  //     justifyContent: "space-between",
  //     alignItems: "center",
  //   },
  //   userIcon: {
  //     right: 10,
  //   },
  //   title: {
  //     fontSize: 30,
  //     fontWeight: "600",
  //     color: colors.darkOrange,
  //   },
  //   inputTitle: {
  //     color: "#2A3256",
  //     fontSize: 16,
  //     fontFamily: "Lexend-Medium",
  //     marginBottom: 5,
  //   },
  //   button: {
  //     backgroundColor: colors.mainButton,
  //     height: 50,
  //     justifyContent: "center",
  //     alignItems: "center",
  //     borderRadius: 10,
  //     flexDirection: "row",
  //     marginTop: 10,
  //   },
  //   loginContainer: {
  //     // marginHorizontal: 20,
  //   },
  //   login: {
  //     fontSize: 16,
  //     fontWeight: "500",
  //     lineHeight: 20,
  //     color: "#FFFFFF",
  //   },
  //   registerContainer: {
  //     alignItems: "center",
  //     justifyContent: "center",
  //     flexDirection: "row",
  //     marginBottom: 10,
  //   },
  //   register: {
  //     fontSize: 16,
  //     color: colors.darkOrange,
  //     fontFamily: "lexend-medium",
  //     fontWeight: "700",
  //   },
  //   error: {
  //     fontSize: 14,
  //     fontFamily: fonts.headerFont,
  //     color: "red",
  //   },
  editProfileButton: {
    marginHorizontal: 20,
    backgroundColor: colors.primary,
    borderRadius: 10,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    elevation: 10,
  },
  addVairentButton: {
    marginVertical: 20,
    backgroundColor: colors.primary,
    borderRadius: 10,
    width: '30%',
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    elevation: 10,
  },
  editProfileButtonText: {
    color: colors.white,
    fontSize: 16,
    fontFamily: fonts.headerFont,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  containerVarent: {
    flexGrow: 1,
    paddingHorizontal: 3,
    paddingVertical:10
  },
  header: {
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 16,
  },
  variantContainer: {
    padding: 22,
    borderColor: colors.lightgrey,
    elevation: 4,
  },
  columnVarient: {
    flexDirection: 'column',
    marginBottom: 8,
  },
  variantColumn: {
    flexDirection: 'column',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  inBoxVarient: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.lightgrey,
    borderRadius: 10,
    height: 60,
    width:270,
    marginBottom: 20,
    backgroundColor: colors.white,
    elevation: 10,
  },
  inputVarient: {
    fontFamily: fonts.headerFont,
    left: 30,
    fontSize: 16,
    color: colors.grey,
    width: 180,
    textTransform: "capitalize",
  },
  picker: {
    fontFamily: fonts.headerFont,
    left: 30,
    fontSize: 16,
    color: colors.grey,
    width: 180,
    textTransform: "capitalize",
  },
  removeButton: {
    backgroundColor: '#FAB70B',
    padding: 8,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  addButton: {
    backgroundColor: '#EF7F14',
    padding: 8,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: 'blue',
    padding: 8,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  innerText2: {
    fontFamily: 'Lexend-Medium',
    left: 30,
    fontSize: 16,
    color: 'grey',
    width: 180,
    textTransform: 'capitalize',
  },
});
export default styles;
